name: Build Bun

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - "bun/**"
      - "SleepyNeko-Studios-Infra-Root-CA.crt"
      - ".github/workflows/bun.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_VARIANT: debian

jobs:
  push:
    name: "yolks:bun_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "1"
          - "1.1"
          - "1.2"
          - "1.3"
          - "latest"
          - "canary"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}

      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Repository to lowercase
        id: lower-repo
        run: |
          echo "repo=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.lower-repo.outputs.repo }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Determine Base Tag
        id: base-tag
        run: |
          if [[ "${{ matrix.tag }}" == "latest" ]]; then
            echo "tag=${{ env.IMAGE_VARIANT }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ matrix.tag }}-${{ env.IMAGE_VARIANT }}" >> $GITHUB_OUTPUT
          fi

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./bun/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BASE_TAG=${{ steps.base-tag.outputs.tag }}
          tags: ${{ env.REGISTRY }}/${{ steps.lower-repo.outputs.repo }}/yolks:bun_${{ matrix.tag }}
